### ISSUE TITLE
How to custom the version of some modules?

### ISSUE THREAD

**Issue by dathudeptrai** [agkphysics/tensorflow-wheels#1]
Hi, thanks for your efforts.

Can you teach me how can I modify this code to support TF 2.12, CUda 12.1.0, cudnn 8.9.0, tensorrt 8.6.1 that match with nvidia tensorflow docker here (https://docs.nvidia.com/deeplearning/frameworks/tensorflow-release-notes/rel-23-04.html). ?. 

I just want to build by myself monthly that match with nvidia latest docker as much as possible. 

Thanks you so much. 

@agkphysics

**Comment by agkphysics** [comment]
You can probably modify the Dockerfile like so to use CUDA 12.1:
```Dockerfile
FROM quay.io/pypa/manylinux2014_x86_64

RUN yum-config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel7/x86_64/cuda-rhel7.repo \
        && yum clean all \
        && yum -y install cuda-12-1 libcudnn8-devel tensorrt-devel libnccl-devel
ENV PATH=/usr/local/cuda-12.1/bin:$PATH
RUN curl -L "https://github.com/bazelbuild/bazelisk/releases/download/v1.16.0/bazelisk-linux-amd64" -o /usr/local/bin/bazel \
        && chmod +x /usr/local/bin/bazel \
        && echo "startup --output_user_root=/tmp/bazel" > /etc/bazel.bazelrc
ENV BAZELISK_HOME=/tmp/bazelisk USER=build

WORKDIR /build
CMD ["/bin/bash"]
```
The reason I used the manylinux2014 image is to maximise Glibc compatibility.

There is an additional patch required for TF 2.12 to make it compile with CUDA 12, which I will add to this repository.

**Comment by dathudeptrai** [comment]
@agkphysics Thank you so much. I saw you just released the tf 2.12 with cuda 12.1, tensorrt 8.6 and python 3.11, so fast :D. How much time does it usually talk to build everything?. Also, may I ask if you plan to build with python 3.8 to match with the newest docker from Nvidia?.

Anyway, it is really helpful since I want to build the triton server docker that support both pytorch and tensorflow. Installing pytorch is easier than TF :D. But tf performance with TF-TRT is much better than pytorch.

**Comment by agkphysics** [comment]
@dathudeptrai

> How much time does it usually talk to build everything?

I have access to a machine with 256 CPU threads, and it takes ~40 mins from start to finish to build a single wheel for a given Python and TensorFlow version.

> may I ask if you plan to build with python 3.8

Yes, I'll build with Python 3.8 at some point.

**Comment by agkphysics** [comment]
@dathudeptrai I've added Python 3.8, 3.9 and 3.10 wheels to the release: https://github.com/agkphysics/tensorflow-wheels/releases/tag/tf_gpu_cuda12.1_cudnn8.9_avx2_mkl_trt8.6

The wheels are in a Google Drive folder since that's easier.

**Comment by dathudeptrai** [comment]
@agkphysics Thanks you so much :D.
